apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: ketanmujumdar/gateway:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: GO_SERVICE_URL
          value: "http://go-api-service.default.svc.cluster.local:8080"
        - name: PYTHON_SERVICE_URL
          value: "http://python-api-service.default.svc.cluster.local:8080"
        - name: PHP_SERVICE_URL
          value: "http://php-api-service.default.svc.cluster.local:8080"
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  type: NodePort
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080