apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-api
  template:
    metadata:
      labels:
        app: go-api
    spec:
      containers:
      - name: go-api
        image: ketanmujumdar/go-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: PHP_SERVICE_URL
          value: "http://php-api-service.default.svc.cluster.local:8080"
---
apiVersion: v1
kind: Service
metadata:
  name: go-api-service
spec:
  selector:
    app: go-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080