apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-api
  template:
    metadata:
      labels:
        app: php-api
    spec:
      containers:
      - name: php-api
        image: ketanmujumdar/php-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: php-api-service
spec:
  selector:
    app: php-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080