apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-api
  template:
    metadata:
      labels:
        app: python-api
    spec:
      containers:
      - name: python-api
        image: ketanmujumdar/python-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: GO_SERVICE_URL
          value: "http://go-api-service.default.svc.cluster.local:8080"
---
apiVersion: v1
kind: Service
metadata:
  name: python-api-service
spec:
  selector:
    app: python-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080